language: bash
sudo: required

services:
  - docker

addons:
  apt:
    sources: [ debian-sid ] # Grab shellcheck from the Debian repo (o_O)
    packages: [ shellcheck ]

env:
  global:
    - CF_DOMAIN=test.org
    - CF_EMAIL=getssl_test_account@mailinator.com
    - CF_KEY=845830354648e4317e1541002f4b778d07b41

before_install:
  - docker pull -a bash

before_script:
  - wget -O test/assert.sh https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh
  - chmod +x test/*.*sh
  - test/prepare_test.org.bash
  - pwd

script:
  - shellcheck getssl dns_scripts/dns_???_* test/*.bash
#  - docker run -it --rm -v 
#  - BVER=bash4.2.45 ../test/cf_tests.bash
